//
//  CarListInteractor.swift
//  CarDemo
//
//  Created by Kumari Ritu Pal on 28/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CarListBusinessLogic
{
    func fetchCarList()
}

protocol CarListDataStore {
    var carList: [CarResponseModel] { get set }
}

class CarListInteractor: CarListBusinessLogic, CarListDataStore
{
    var presenter: CarListPresentationLogic?
    var carList: [CarResponseModel] = []
    
    func fetchCarList() {
        self.carList = DataManager.shared.allCars
        self.isCarListEmpty() ? self.presenter?.onCarListFetchFailed() : self.presenter?.onCarListFetchSucceed(list: self.carList)
    }
    
    private func isCarListEmpty() -> Bool {
        self.carList.isEmpty
    }
}
