//
//  CarListPresenter.swift
//  CarDemo
//
//  Created by Kumari Ritu Pal on 28/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CarListPresentationLogic
{
//  func presentSomething(response: CarList.Something.Response)
}

class CarListPresenter: CarListPresentationLogic
{
  weak var viewController: CarListDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: CarList.Something.Response)
//  {
//    let viewModel = CarList.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
