//
//  CarListInteractor.swift
//  CarDemo
//
//  Created by Kumari Ritu Pal on 28/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CarListBusinessLogic
{
//  func doSomething(request: CarList.Something.Request)
}

protocol CarListDataStore
{
  //var name: String { get set }
}

class CarListInteractor: CarListBusinessLogic, CarListDataStore
{
  var presenter: CarListPresentationLogic?
//  var worker: CarListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: CarList.Something.Request)
//  {
//    worker = CarListWorker()
//    worker?.doSomeWork()
//
//    let response = CarList.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
}
