//
//  CarListViewController.swift
//  CarDemo
//
//  Created by Kumari Ritu Pal on 28/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CarListDisplayLogic: AnyObject {
    func loadVehicleList(viewModel: CarListViewModel)
    func showEmptyView()
}

class CarListViewController: BaseViewController {
    
    @IBOutlet weak var tableViewVehicle: UITableView!
    // MARK: Variables
    private var vehicleList: [TableCellConfigItemProtocol] = []
    
    var interactor: CarListBusinessLogic?
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        getCarList()
    }
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = CarListInteractor()
        let presenter = CarListPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
        setupTableView()
    }
    
    // MARK:- Functions
    private func getCarList() {
        showSpinner()
        interactor?.fetchCarList()
    }
    
    private func setupTableView() {
        self.tableViewVehicle.dataSource = self
        self.tableViewVehicle.delegate = self
    }
    
    private func loadDataInTableView(viewModel: CarListViewModel) {
        self.vehicleList = viewModel.vehicleList
        tableViewVehicle.reloadData()
    }
}

extension CarListViewController: CarListDisplayLogic {
    
    func loadVehicleList(viewModel: CarListViewModel) {
        hideSpinner()
        loadDataInTableView(viewModel: viewModel)
    }
    
    func showEmptyView() {
        hideSpinner()
    }
}

//MARK:- Table view DataSource and Delegate
extension CarListViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        self.vehicleList.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cellModel = self.vehicleList[indexPath.row]
        let drawer = cellModel.cellConfigure
        let cell = drawer.dequeueCell(tableView, cellForRowAt: indexPath)
        drawer.configureCell(cell, withItem: cellModel)
        return cell
    }
}
